version: '3'

services:
    mongodb:
        container_name: crush-management-mongo
        image: mongo:latest
        volumes:
            - ./docker-config/database:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - "27017:27017"

    crush-management:
        depends_on:
            - mongodb
        container_name: crush-management-node
        build:
            context: ./
        image: crush-management:1.0
        volumes:
            - "./:/var/www/app"
        links:
            - "mongodb:mongodb"
        ports:
            - "3000:3000"
